// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";
import { group } from "k6";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  group("location and branch", function() {
    postman[Request]({
      name: "https://cdms-dashboard-api-dev.jba.co.id/v2/branch/list",
      id: "a3fdb6c8-23cd-4b15-8824-f6882032099e",
      method: "GET",
      address: "https://cdms-dashboard-api-dev.jba.co.id/v2/branch/list",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name: "https://cdms-dashboard-api-dev.jba.co.id/v2/branchlocation/list",
      id: "096ea0e5-688e-487c-915d-e346bd2892bb",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/branchlocation/list",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });
  });

  group("seller", function() {
    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/bpkp/outstanding/{seller_id}/{expired_start}/{expired_end}/{location_id}",
      id: "8bd271aa-0bd3-4e10-83a0-fc5a7a40904f",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/bpkp/outstanding/110/2020-01-01/2020-10-31/1",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name: "https://cdms-dashboard-api-dev.jba.co.id/v2/seller/list",
      id: "a1b624f4-2e24-4007-91d9-92967a21b166",
      method: "GET",
      address: "https://cdms-dashboard-api-dev.jba.co.id/v2/seller/list",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/sales-seller/{seller_id}/{year}",
      id: "32de9991-a931-45ee-a688-ced573906535",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/sales-seller/110/2020",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });
  });

  group("auction", function() {
    postman[Request]({
      name: "https://cdms-dashboard-api-dev.jba.co.id/v2/auction/schedule/",
      id: "1077d2d2-8ea2-4a7a-87cc-3b2ac9d51570",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/auction/schedule/2020-10-01/2020-10-31",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/auction/tax/update-status",
      id: "9309b845-831e-4472-a660-168a8f1b16ec",
      method: "POST",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/auction/tax/update-status",
      data: {
        auction_list_id: "5",
        auction_list_status: "1"
      },
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/auction/risalah-lelang/{seller_id}/{start_date}/{end_date}/{location_id}",
      id: "1c6cf198-2c28-4d5b-8cd3-8c235ff82e68",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/auction/risalah-lelang/110/2020-10-01/2020-10-31/11",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/auction/payment/{seller_id}/{location_id}/{start_date}/{end_date}",
      id: "d43fc59e-5c4c-4571-8093-29b4f146dc39",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/auction/payment/110/11/2020-10-01/2020-10-31",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/auction/mobilization/{seller_id}/{location_id}/{start_date}/{end_date}",
      id: "42fcb2bd-5ae4-4fdd-843f-9c11ad5a306f",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/auction/mobilization/110/11/2020-10-01/2020-10-31",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name: "https://cdms-dashboard-api-dev.jba.co.id/v2/post-auction-note",
      id: "b7f232ff-0355-455c-9668-65205916ed33",
      method: "POST",
      address: "https://cdms-dashboard-api-dev.jba.co.id/v2/post-auction-note",
      data: {
        note: "testing",
        vehicle_id: "5"
      },
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name: "https://cdms-dashboard-api-dev.jba.co.id/v2/update-auction-list",
      id: "e120d523-0179-4323-b95a-4b1fd5a2b3da",
      method: "POST",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/update-auction-list",
      data: {
        columns: "7",
        auction_list_id: "5"
      },
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });
  });

  group("Summary Seller", function() {
    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/{seller_id}/stock/location/{start_date}/{end_date}/{location}",
      id: "cc2d95ca-9aed-49f4-97eb-483cd1958765",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/{seller_id}/stock/location/{start_date}/{end_date}/{location}",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/{seller_id}/stock/location-monthly/{year}/{location}",
      id: "1b80705a-28c0-41b6-8b8d-ee942acf36cb",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/110/stock/location-monthly/2020/11",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/{seller_id}/stock/location-detail/{end_date}/{location}",
      id: "5aa9a8fe-994c-4f3a-8ba0-0e23832ad3aa",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/110/stock/location-detail/2020-10-31/11",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/{seller_id}/stock/{start_date}/{end_date}/{location}/{summarizer}",
      id: "1da18143-19ae-433b-bbc5-496e2ceebd07",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/110/stock/location/2020-10-01/2020-10-31/11",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/{seller}/stock/yearly/{year}/{month}",
      id: "33e20a2e-6c63-4942-bd4b-d4ae3436a0e8",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/110/stock/yearly/2020/1",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/{seller_id}/stock/monthly/{month}/{year}",
      id: "52007ac1-245d-4828-a834-83aea1d62c4f",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/110/stock/monthly/1/2020",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/{seller_id}/stock/sold/{start_date}/{end_date}",
      id: "fc5844cb-0940-44f8-ae81-b0b96e9d452c",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/110/stock/sold/2020-08-01/2020-10-31",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/{seller_id}/auction/yearly/{yearly}",
      id: "c5a3c37e-59f1-4d69-bf6d-ec9dc9d9993a",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/110/auction/yearly/2020",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/{Seller_id}/auction/monthly/{month}/{year}",
      id: "fe351abb-49d7-428d-a863-b0ba8f0a0db9",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/110/auction/monthly/10/2020",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/{Seller_id}/auction/monthly-sold[/{month}/{year}",
      id: "f4f3e529-e49a-4af2-91b1-47ab09f115b2",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/110/auction/monthly-sold/10/2020",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });
  });

  group("summary customer", function() {
    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/customer/{location_id}/yearly/{year}",
      id: "6ec4e9d7-d5b2-4ed5-8aba-1c6e7a38330b",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/customer/11/yearly/2020",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/customer/{location_id}/monthly/{month}/{year}",
      id: "a84e9347-9f6a-43d9-9cc3-789a80aec363",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/customer/11/monthly/10/2020",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });
  });

  group("sales speed", function() {
    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/{Seller_id}/auction/sales-speed/yearly/{year}",
      id: "bf1f3d31-8013-40cf-bed6-880dae408521",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/summary/seller/110/auction/sales-speed/yearly/2020",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/sales-speed/pie-chart/{start_date}/{end_date}/{seller_id}/{location_id}",
      id: "c1a415dd-9de6-4295-88fb-89e1c2b2dd1f",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/sales-speed/pie-chart/2020-10-01/2020-10-30/110/11",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/sales-speed/detail/{start_date}/{end_date}/{seller_id}/{location_id}",
      id: "4a63640f-d9e5-417d-8173-d15695ea8b1e",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/sales-speed/detail/2020-10-01/2020-10-31/110/11",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/sales-speed/detail-index/{index_auction}/{end_date}/{seller_id}/{location_id}",
      id: "d1b6b0cf-d1b0-40df-bb08-ceca2414e39b",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/sales-speed/detail-index/21/2020-08-01/110/11",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });
  });

  group("vehicles", function() {
    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/unit-performance/{location_id}",
      id: "289fd3c8-5a19-48f8-860d-d36e90cfd6f2",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/unit-performance/11",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });
  });

  group("salles", function() {
    postman[Request]({
      name: "https://cdms-dashboard-api-dev.jba.co.id/v2/data-brh/{year}",
      id: "8d5e1c28-6713-42d6-806c-2039d28fb7b8",
      method: "GET",
      address: "https://cdms-dashboard-api-dev.jba.co.id/v2/data-brh/2020",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name: "https://cdms-dashboard-api-dev.jba.co.id/v2/data-bro/{year}",
      id: "36e197e4-c8b9-4e3e-b852-b65df40a3f1b",
      method: "GET",
      address: "https://cdms-dashboard-api-dev.jba.co.id/v2/data-bro/2020",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/dashboard-sales-brh-bro/{year}/{month}",
      id: "99b98dfb-1859-4815-8017-0f9ea5855fe4",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/dashboard-sales-brh-bro/2020/01",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/dashboard-sales-monthly/{sales_group}/{year}/{sales_name}",
      id: "83a4d8b6-b29f-4b7c-b7fb-fd582dc15eda",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/dashboard-sales-monthly/brh/2020/luthfy",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/dashboard-sales-get-brh",
      id: "22db0e65-06e9-40f0-9f59-8e8991d61d99",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/dashboard-sales-get-brh",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/sales-branch/by-location-year/{location_id}/{year}",
      id: "66291a8a-a1b9-473e-8dc3-238c3aedcb10",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/sales-branch/by-location-year/11/2020",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });

    postman[Request]({
      name:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/sales-branch/by-location/{location_id}/{start_date}/{end_date}",
      id: "3ee4ed0d-0d44-4f41-a8ea-d9f37937218f",
      method: "GET",
      address:
        "https://cdms-dashboard-api-dev.jba.co.id/v2/sales-branch/by-location/11/2020-08-01/2020-11-31",
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });
  });

  group("Seller Login", function() {
    postman[Request]({
      name: "https://cdms-dashboard-api-dev.jba.co.id/seller/login",
      id: "79a5f5a3-410a-4e2c-81b1-787067c48e59",
      method: "POST",
      address: "https://cdms-dashboard-api-dev.jba.co.id/seller/login",
      data: {
        username: "info@oto.co.id",
        password: "qwe123"
      },
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });
  });

  group("Internal Login", function() {
    postman[Request]({
      name: "https://cdms-dashboard-api-dev.jba.co.id/seller/login",
      id: "997f9ff4-ce5c-4f0b-93d4-7adfdfa33bf8",
      method: "POST",
      address: "https://cdms-dashboard-api-dev.jba.co.id/user/login",
      data: {
        username: "syslgk",
        password: "qwe123"
      },
      auth(config, Var) {
        config.headers.Authorization =
          "Bearer eyJpdiI6IllsVFRQNFNWeWVZellrMmRmSUxXdWc9PSIsInZhbHVlIjoiQ2pTUzZEWGVVNDhcL255YmZkMGRiZmVtdnNiSjU2ZFVCbFNHbG9kenQyaUE9IiwibWFjIjoiZDAzMjkxYmQ4NDZjMDQwZTA5NTBhOTdhYTgzODY1ZjRmNDdhMzIxNzk4MDJjMWYzY2Q5ZjRhNTk0NDQ2YTMzZiJ9";
      }
    });
  });
}
